#!/usr/bin/env python3
import argparse
import hashlib
import json
import re
import unicodedata
import urllib.parse
import urllib.request
from pathlib import Path


def norm(value):
    value = unicodedata.normalize("NFKD", str(value or ""))
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    return re.sub(r"\s+", " ", value).strip().casefold()


def license_allows_game(url):
    value = str(url or "").lower()
    if not value:
        return False
    if "publicdomain/zero/" in value or "publicdomain/mark/" in value:
        return True
    if "creativecommons.org/licenses/by/" in value:
        return True
    if "creativecommons.org/licenses/by-sa/" in value:
        return True
    return False


def https_url(value):
    value = str(value or "").strip()
    if value.startswith("http://"):
        return "https://" + value[7:]
    return value


def fetch_chart(client_id):
    params = urllib.parse.urlencode({
        "client_id": client_id,
        "format": "json",
        "limit": 200,
        "country": "BRA",
        "order": "trending",
    })
    url = "https://api.jamendo.com/v3.0/charts/track/?" + params
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "musicadodia-auto-selector/1.0"},
    )
    with urllib.request.urlopen(req, timeout=35) as response:
        data = json.load(response)
    headers = data.get("headers") or {}
    if headers.get("status") not in (None, "success"):
        raise RuntimeError(headers.get("error_message") or "Jamendo API error")
    return data.get("results") or []


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", default="catalog.json")
    parser.add_argument("--date", required=True)
    parser.add_argument("--client-id", required=True)
    parser.add_argument("--output", default="auto-selection.json")
    parser.add_argument("--replace", action="store_true")
    args = parser.parse_args()

    catalog_path = Path(args.catalog)
    catalog = json.loads(catalog_path.read_text(encoding="utf-8")) if catalog_path.exists() else {"songs": []}
    songs = catalog.get("songs") if isinstance(catalog.get("songs"), list) else []

    existing = next((song for song in songs if str(song.get("date", "")) == args.date), None)
    if existing:
        if not args.replace:
            result = {"status": "skip", "reason": "date_already_has_song", "date": args.date}
            Path(args.output).write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            print(json.dumps(result, ensure_ascii=False))
            return
        if not bool(existing.get("autoGenerated")):
            result = {"status": "skip", "reason": "manual_song_has_priority", "date": args.date}
            Path(args.output).write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            print(json.dumps(result, ensure_ascii=False))
            return

    used_pairs = {(norm(song.get("artist")), norm(song.get("title"))) for song in songs}
    used_ids = {str(song.get("autoProviderId", "")).strip() for song in songs if song.get("autoProviderId")}
    recent_artists = {
        norm(song.get("artist"))
        for song in sorted(songs, key=lambda item: str(item.get("date", "")), reverse=True)[:12]
    }

    candidates = []
    for track in fetch_chart(args.client_id):
        track_id = str(track.get("id", "")).strip()
        title = str(track.get("name", "")).strip()
        artist = str(track.get("artist_name", "")).strip()
        download = https_url(track.get("audiodownload"))
        license_url = https_url(track.get("license_ccurl"))
        try:
            duration = float(track.get("duration") or 0)
        except (TypeError, ValueError):
            duration = 0

        if not track_id or not title or not artist:
            continue
        if track_id in used_ids or (norm(artist), norm(title)) in used_pairs:
            continue
        if duration < 45:
            continue
        if track.get("audiodownload_allowed") is not True or not download.startswith("https://"):
            continue
        if not license_allows_game(license_url):
            continue

        released = str(track.get("releasedate", "")).strip()
        year_match = re.match(r"(19\d{2}|20\d{2})", released)
        candidates.append({
            "status": "selected",
            "date": args.date,
            "provider": "jamendo",
            "provider_id": track_id,
            "title": title,
            "artist": artist,
            "audio_url": download,
            "release_year": year_match.group(1) if year_match else "",
            "cover_url": https_url(track.get("image") or track.get("album_image")),
            "source_url": https_url(track.get("shareurl") or track.get("shorturl")),
            "license_url": license_url,
            "difficulty": "Médio",
            "duration": duration,
            "recent_artist": norm(artist) in recent_artists,
        })

    if not candidates:
        raise SystemExit("Nenhuma faixa brasileira elegível e reutilizável foi encontrada no provedor.")

    fresh_artist = [item for item in candidates if not item["recent_artist"]]
    pool = fresh_artist or candidates
    top = pool[: min(40, len(pool))]
    seed = int(hashlib.sha256(("musicadodia|" + args.date).encode("utf-8")).hexdigest()[:16], 16)
    selected = dict(top[seed % len(top)])
    selected.pop("recent_artist", None)
    selected["auto_replace"] = bool(args.replace)

    Path(args.output).write_text(json.dumps(selected, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(selected, ensure_ascii=False))


if __name__ == "__main__":
    main()
